### ISSUE TITLE
Search by property and/or series

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/support.pmp.io#10]
The searcher currently only let's you look for `?profile=series`.  But that's not always useful since some publishers use a `property` instead.

So should probably expand the searcher to have an additional checkbox for Property.

**Comment by kookster** [comment]
a searcher may not know up front what is a series or property - search `collections` in general?

**Comment by cavis** [comment]
Err... not sure that's what I'm after.  So here's the use-case: I want to find "The Moth" in the PMP, and then search for all episodes of "The Moth".

The first is probably a text-search - and to narrow it down, I was thinking of restricting that text-search to 2 specific profile types that are commonly used to group stories/episodes.

(Note: will also have to expand the interface to let you search `?collection=guid` somehow.

**Comment by cavis** [comment]
Hey, looks like I already did this.  Congratulations, me!
