### ISSUE TITLE
Program Diagrams for User Guide - Keep!

### ISSUE THREAD

**Issue by JNemic** [publicmediaplatform/support.pmp.io#25]
![slide1](https://cloud.githubusercontent.com/assets/4427754/8828689/7542799c-3061-11e5-87c4-81c629ef72c3.PNG)
![slide2](https://cloud.githubusercontent.com/assets/4427754/8828690/7548faba-3061-11e5-9197-0ec41329b968.PNG)

**Comment by pkarman** [comment]
fwiw the first diagram is very close to how Marketplace from APM is organized in the PMP

**Comment by JNemic** [comment]
Yes, though I didn't want to use an actual program in the event that something changed.

**Comment by pkarman** [comment]
understood. I just wanted to acknowledge that (a) they are very nice, helpful pictures, and (b) validate that there are real examples of organizing this way.

**Comment by cavis** [comment]
@pkarman you think those diagrams will make sense to your average non-developer users?  I think Jeff was (correctly) going for concept-over-accuracy here.

To be truly "accurate" for the implementation, he would have to clutter that diagram up with many more lines.  For instance: the Property would need a line to every other box in the diagram.

**Comment by pkarman** [comment]
@cavis yes they seem apt for non-developers, and agreed about simpler lines. I was mentally drawing in the "links" myself, but that was only for completeness. I interpreted the lines as conceptual.
